#!/bin/bash
source $HOME/.bashrc
CYAN='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${CYAN}apt-get update${NC}"
sudo apt-get update

echo -e "${CYAN}apt-get dist-upgrade -y"
sudo apt-get dist-upgrade -y

echo -e "${CYAN}apt-get update${NC}"
sudo apt-get update

echo -e "${CYAN}apt-get upgrade${NC}"
sudo apt-get upgrade -y

echo -e "${CYAN}apt autoclean${NC}"
sudo apt autoclean -y

echo -e "${CYAN}apt autoremove${NC}"
sudo apt autoremove -y

echo -e "${CYAN}apt clean${NC}"
sudo apt clean -y

echo -e "${GREEN}FINISHED${NC}"
